name: Build and Push to Dokku

on:
  workflow_run: 
    workflows: [ "Java CI with Gradle" ]
    branches: [ "main" ]
    types: 
      - completed
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download workflow artifact
        uses: dawidd6/action-download-artifact@v2.26.1
        with:
          workflow: Java CI with Gradle
          name: Package
          path: build/libs
      - name: Set up qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@{{ secrets.DOKKU_HOST }}:22/{{ secrets.DOKKU_APP_NAME }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          deploy_docker_image: ${{ secrets.DOCKER_IMAGE }}:${{ secrets.DOCKER_TAG }}
